language: scala
scala:
   2.11.2
jdk:
  - oraclejdk8
before_cache:
  - rm -f ./node_modules/.bin/which # <-- workaround for https://github.com/travis-ci/travis-ci/issues/5092
cache:
  bundler: true
  directories:
    - node_modules
before_install:
  - rvm install 2.5.1
  - ruby --version
  - gem install bundler -v 1.16.1
  - bundle --version
  - java -version
install:
  - npm install
  - bundle install

script: ./bin/deploy

env:
  global:
    # This is staging only
    - GATSBY_DISALLOW_ROBOTS=$([ "$TRAVIS_TAG" == "" ] && echo "$STAGING_DISALLOW_ROBOTS")

    - PREFIX_FOLDER=$([ "$TRAVIS_PULL_REQUEST" != "false" ] && echo "pr-$TRAVIS_PULL_REQUEST")
    - HOST=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_HOST" || echo "$STAGING_HOST")
    - APP_HOST=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_APP_HOST" || echo "$STAGING_APP_HOST")
    - API_HOST=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_API_HOST" || echo "$STAGING_API_HOST")
    - GATSBY_HOST=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_HOST" || echo "$STAGING_HOST")
    - GATSBY_APP_HOST=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_APP_HOST" || echo "$STAGING_APP_HOST")
    - BLOG_HOST=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_BLOG_HOST" || echo "$STAGING_BLOG_HOST")
    - ROLLBAR_TOKEN=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_ROLLBAR_TOKEN" || echo "$STAGING_ROLLBAR_TOKEN")
    - URL_BASE=$([ "$PREFIX_FOLDER" != "" ] && echo "/$PREFIX_FOLDER")
    - GTM_ID=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_GTM_ID" || echo "$STAGING_GTM_ID")
    - GA_ID=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_GA_ID" || echo "$STAGING_GA_ID")
    - GATSBY_VWO_ID=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_VWO_ID")
    - COOKIE_DOMAIN=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_COOKIE_DOMAIN" || echo "$STAGING_COOKIE_DOMAIN")
    - CF_DISTRIBUTION=$([ "$TRAVIS_TAG" != "" ] && echo "$PROD_CF_DISTRIBUTION" || echo "$STAGING_CF_DISTRIBUTION")
    - S3_FORCE=$(git log $TRAVIS_PULL_REQUEST_SHA -1 --pretty=%B | grep -E "^\[#s3 .*force.*]" --ignore-case)
    - S3_CFG=$(git log $TRAVIS_PULL_REQUEST_SHA -1 --pretty=%B | grep -E "^\[#s3 .*configure.*]" --ignore-case)
