import bear from '../../static/employees/Bearpot_Team.jpg'
import agathe from '../../static/employees/DSC01861.jpg'
import amar from '../../static/employees/DSC01793.jpg'
import apoorv from '../../static/employees/Bearpot_Team.jpg'
import baku from '../../static/employees/DSC02034.jpg'
import bugra from '../../static/employees/Bearpot_Team.jpg'
import debora from '../../static/employees/DSC01981.jpg'
import ekaterina from '../../static/employees/DSC01833.jpg'
import emma from '../../static/employees/Bearpot_Team.jpg'
import emma2 from '../../static/employees/DSC02058.jpg'
import fenne from '../../static/employees/DSC01923.jpg'
import florian from '../../static/employees/DSC01945.jpg'
import geneva from '../../static/employees/DSC01847.jpg'
import hana from '../../static/employees/DSC02026.jpg'
import isabel from '../../static/employees/Bearpot_Team.jpg'
import itziar from '../../static/employees/DSC01810.jpg'
import jelle from '../../static/employees/DSC01976.jpg'
import jeremy from '../../static/employees/DSC01815.jpg'
import josiah from '../../static/employees/DSC01929.jpg'
import julian from '../../static/employees/DSC02047.jpg'
import kado from '../../static/employees/DSC01820.jpg'
import katharina from '../../static/employees/DSC02003.jpg'
import kaya from '../../static/employees/DSC02072.jpg'
import kevin from '../../static/employees/DSC01800.jpg'
import laura from '../../static/employees/DSC01881.jpg'
import laura2 from '../../static/employees/DSC01856.jpg'
import lisa from '../../static/employees/Bearpot_Team.jpg'
import mai from '../../static/employees/DSC02011.jpg'
import marc from '../../static/employees/Bearpot_Team.jpg'
import matthijs from '../../static/employees/DSC01869.jpg'
import max from '../../static/employees/DSC01825.jpg'
import meriem from '../../static/employees/DSC01783.jpg'
import mia from '../../static/employees/DSC01914.jpg'
import mia2 from '../../static/employees/DSC01898.jpg'
import mirko from '../../static/employees/Bearpot_Team.jpg'
import monika from '../../static/employees/Bearpot_Team.jpg'
import munya from '../../static/employees/DSC01903.jpg'
import priscilla from '../../static/employees/Bearpot_Team.jpg'
import pierre from '../../static/employees/DSC01802.jpg'
import sarah from '../../static/employees/DSC01970.jpg'
import sonya from '../../static/employees/Bearpot_Team.jpg'
import stefan from '../../static/employees/DSC01941.jpg'
import tabea from '../../static/employees/DSC01838.jpg'
import thomas from '../../static/employees/DSC02080.jpg'
import wiktoria from '../../static/employees/DSC02001.jpg'

export default [
  {
    name: 'Agathe',
    last_name: 'Badia',
    title: 'Talent Rep',
    favorite_color: 'Blue',
    linkedin: 'https://fr.linkedin.com/in/agathe-badia-b6712b59/en',
    twitter: '',
    github: '',
    image: agathe,
  },
  {
    name: 'Amar',
    last_name: 'Ahlers',
    title: 'Customer Success Manager',
    favorite_color: 'Cyan',
    linkedin: 'https://www.linkedin.com/in/amarahlers/',
    twitter: '',
    github: '',
    image: agathe,
  },
  {
    name: 'Apoorv',
    last_name: 'Ahlawat',
    title: 'Performance Marketing Manger',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: apoorv,
  },
  {
    name: 'Buğra',
    last_name: 'Kantar',
    title: 'Digital Designer',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: bugra,
  },
  {
    name: 'Debora',
    last_name: 'Lasoen',
    title: 'Head of Talent Management',
    favorite_color: 'orange',
    linkedin: 'https://th.linkedin.com/in/dlasoen',
    twitter: '',
    github: '',
    image: debora,
  },
  {
    name: 'Ekaterina',
    last_name: 'Kromina',
    title: 'Global Events Manager',
    favorite_color: 'Orange',
    linkedin: 'https://www.linkedin.com/in/ekaterina-kromina-95478b6a/',
    twitter: 'https://twitter.com/kromina_ek',
    github: '',
    image: ekaterina,
  },
  {
    name: 'Emma',
    last_name: 'Hunt',
    title: 'People Operations Manager',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: emma,
  },
  {
    name: 'Emma',
    last_name: 'Tracey',
    title: 'Co-Founder',
    favorite_color: 'Mustard',
    linkedin: 'https://de.linkedin.com/in/emmalouisetracey',
    twitter: '',
    github: 'https://github.com/emmalou',
    image: emma2,
  },
  {
    name: 'Fenne',
    last_name: 'Buitenrust Hettema',
    title: 'Product Designer',
    favorite_color: 'black',
    linkedin: 'https://www.linkedin.com/in/fenne-buitenrust-hettema-ab3abab8/',
    twitter: '',
    github: '',
    image: fenne,
  },
  {
    name: 'Florian',
    last_name: 'Marandet',
    title: 'Business Intelligence',
    favorite_color: 'IKB 191',
    linkedin: 'https://www.linkedin.com/in/florianmarandet/',
    twitter: '',
    github: 'Olfairn',
    image: florian,
  },
  {
    name: 'Geneva',
    last_name: 'Brooks',
    title: 'Talent Rep',
    favorite_color: 'Green',
    linkedin: 'https://www.linkedin.com/in/geneva-brooks/',
    twitter: '',
    github: '',
    image: geneva,
  },
  {
    name: 'Hana',
    last_name: 'Ensley',
    title: 'Customer Success Manager',
    favorite_color: 'Green',
    linkedin: '',
    twitter: '',
    github: '',
    image: hana,
  },
  {
    name: 'Isabel',
    last_name: 'Hübner',
    title: 'Accountant & Operations Manager',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: isabel,
  },
  {
    name: 'Itziar',
    last_name: 'Merladet',
    title: 'Talent Rep',
    favorite_color: 'Blue',
    linkedin: 'https://www.linkedin.com/in/itziarmerladet/',
    twitter: '',
    github: '',
    image: itziar,
  },
  {
    name: 'Jelle',
    last_name: 'Groot',
    title: 'Head of Client Relations',
    favorite_color: 'White',
    linkedin: 'https://nl.linkedin.com/in/jellegroot',
    twitter: '',
    github: '',
    image: jelle,
  },
  {
    name: 'Jeremy',
    last_name: 'Bello',
    title: 'Customer Success Manager',
    favorite_color: 'green',
    linkedin: 'https://www.linkedin.com/feed/',
    twitter: '',
    github: '',
    image: jeremy,
  },
  {
    name: 'Josiah',
    last_name: 'McGarvie',
    title: 'Video Producer',
    favorite_color: 'Navy Blue',
    linkedin: 'https://www.linkedin.com/in/josiah-mcgarvie-88a087a1/',
    twitter: '',
    github: '',
    image: josiah,
  },
  {
    name: 'Julian',
    last_name: 'Schnute',
    title: 'Operations Manager',
    favorite_color: 'Skin colour (White)',
    linkedin: '',
    twitter: '',
    github: '',
    image: julian,
  },
  {
    name: 'Kado',
    last_name: 'Damball',
    title: 'Software Developer',
    favorite_color: 'Navy Blue',
    linkedin: 'https://www.linkedin.com/in/kado-damball-68835856',
    twitter: 'kdamball',
    github: 'kdamball',
    image: kado,
  },
  {
    name: 'Katharina',
    last_name: 'Kretschmer',
    title: 'Customer Success Manager',
    favorite_color: 'red',
    linkedin: 'https://www.linkedin.com/in/katharina-kretschmer-07254772/',
    twitter: '',
    github: '',
    image: katharina,
  },
  {
    name: 'Kaya',
    last_name: 'Taner',
    title: 'Founder & CEO',
    favorite_color: 'Navy, Grey',
    linkedin: 'http://linkedin.com/in/kayataner',
    twitter: 'kayataner1',
    github: 'ktaner',
    image: kaya,
  },
  {
    name: 'Kevin',
    last_name: 'Butler',
    title: 'Software Developer',
    favorite_color: 'OrangeBoxOrange',
    linkedin: '',
    twitter: '',
    github: 'ryman',
    image: kevin,
  },
  {
    name: 'Laura',
    last_name: 'Godolphin',
    title: 'Talent Rep',
    favorite_color: 'Purple',
    linkedin: '',
    twitter: '',
    github: '',
    image: laura2,
  },
  {
    name: 'Laura',
    last_name: 'Schukkink',
    title: 'Netherlands Team Lead',
    favorite_color: 'Teal',
    linkedin: 'https://www.linkedin.com/in/lauraschukkink/',
    twitter: '',
    github: '',
    image: laura,
  },
  {
    name: 'Lisa',
    last_name: 'Gaertner',
    title: 'Talent Relocation Manager',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: lisa,
  },
  {
    name: 'Mai',
    last_name: 'Luong',
    title: 'Talent Rep',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: mai,
  },
  {
    name: 'Marc',
    last_name: 'Redemske',
    title: 'Software Developer',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: marc,
  },
  {
    name: 'Matthijs',
    last_name: 'den Boer',
    title: 'Business Development Manager',
    favorite_color: 'Bordeaux Red',
    linkedin: 'https://www.linkedin.com/in/matthijs-den-boer-5a74b6b3/',
    twitter: '',
    github: '',
    image: matthijs,
  },
  {
    name: 'Max',
    last_name: 'Philipp',
    title: 'Data Scientist',
    favorite_color: 'Lightblue',
    linkedin: 'www.linkedin.com/in/max-philipp',
    twitter: '',
    github: 'https://github.com/MPhilippHWR',
    image: max,
  },
  {
    name: 'Meriem',
    last_name: 'Hebaz',
    title: 'Talent Rep',
    favorite_color: 'Dark Blue',
    linkedin: 'https://www.linkedin.com/in/meriem-hebaz-5239a3115/',
    twitter: '',
    github: '',
    image: meriem,
  },
  {
    name: 'Mia',
    last_name: 'Bijman',
    title: 'Customer Success Manager',
    favorite_color: 'cobalt blue',
    linkedin: 'https://www.linkedin.com/in/miabijman/',
    twitter: '@miabijman ‏',
    github: 'https://github.com/BirdMia',
    image: mia,
  },
  {
    name: 'Mia',
    last_name: 'Mosler',
    title: 'Talent Rep',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: mia2,
  },
  {
    name: 'Mirko',
    last_name: 'Nitschke',
    title: 'Business Development Manager',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: mirko,
  },
  {
    name: 'Monika',
    last_name: 'Marinova',
    title: 'Talent Rep',
    favorite_color: 'Pink',
    linkedin: 'https://www.linkedin.com/in/monika-marinova-0aba8b110/',
    twitter: '',
    github: '',
    image: monika,
  },
  {
    name: 'Munya',
    last_name: 'Mangwana',
    title: 'Customer Success Manager',
    favorite_color: 'Navy Blue',
    linkedin: '',
    twitter: '',
    github: '',
    image: munya,
  },
  {
    name: 'Priscilla',
    last_name: 'Tenggara',
    title: 'B2B Marketing',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: priscilla,
  },
  {
    name: 'Pierre',
    last_name: 'Le Buhan',
    title: 'Business Developer',
    favorite_color: 'Green',
    linkedin: '',
    twitter: '',
    github: '',
    image: pierre,
  },
  {
    name: 'Sarah',
    last_name: 'Blech',
    title: 'Customer Development Manager',
    favorite_color: '',
    linkedin: '',
    twitter: '',
    github: '',
    image: sarah,
  },
  {
    name: 'Sonya',
    last_name: 'Klaus',
    title: 'Talent Rep',
    favorite_color: 'turquoise',
    linkedin: '',
    twitter: '',
    github: '',
    image: sonya,
  },
  {
    name: 'Stefan',
    last_name: 'Kingham',
    title: 'Content Marketing Manager',
    favorite_color: 'Blue',
    linkedin: '',
    twitter: '',
    github: '',
    image: agathe,
  },
  {
    name: 'Tabea',
    last_name: 'Müller',
    title: 'BI and Finance Team Lead',
    favorite_color: 'Burgundy',
    linkedin: 'https://de.linkedin.com/in/tabea-müller-384a10115',
    twitter: '',
    github: '',
    image: tabea,
  },
  {
    name: 'Thomas',
    last_name: 'Thiele',
    title: 'VP Operations',
    favorite_color: 'Green, Orange',
    linkedin: 'https://www.linkedin.com/in/computhomas/',
    twitter: 'computhomas',
    github: 'https://github.com/computhomas',
    image: thomas,
  },
  {
    name: 'Wiktoria',
    last_name: 'Vowles',
    title: 'Customer Success Manager',
    favorite_color: '#ffcc00',
    linkedin: 'https://www.linkedin.com/in/wiktoria-vowles-919821a4',
    twitter: 'https://twitter.com/WiktaV',
    github: '',
    image: wiktoria,
  },
]
